apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "awx.fullname" . }}-confd
  labels:
    app.kubernetes.io/name: {{ include "awx.name" . }}
    helm.sh/chart: {{ include "awx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- $root := . -}}
{{ range $path, $bytes := .Files.Glob "files/conf.d/*" }}
{{- $contents := $root.Files.Get $path }}
  {{ base $path }}: {{ tpl $contents $root | b64enc | quote }}
{{- end -}}
