apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "awx.fullname" . }}-db-migrate
  labels:
    app.kubernetes.io/name: {{ include "awx.name" . }}
    helm.sh/chart: {{ include "awx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 300
  template:
    name: db-migrate
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: "{{ .Values.postgresql.image.registry }}/{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          command:
            - sh
            - -c
            - "until pg_isready -h {{ .Release.Name }}-postgresql -U {{ .Values.postgresql.postgresqlUsername }} -p 5432; do echo waiting for database; sleep 2; done;"
      containers:
        - name: awx-management
          image: "{{ .Values.awx_task.image.repository }}:{{ .Values.awx_task.image.tag }}"
          command:
            - "awx-manage"
            - "migrate"
            - "--noinput"
          volumeMounts:
            - mountPath: /etc/tower
              name: {{ include "awx.fullname" . }}
          env:
            - name: DATABASE_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: DATABASE_NAME
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: DATABASE_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: MEMCACHED_HOST
              value: {{ .Release.Name }}-memcached
            - name: RABBITMQ_HOST
              value: {{ .Release.Name }}-rabbitmq
          resources: {}
      volumes:
        - name: {{ include "awx.fullname" . }}
          configMap:
            name: {{ include "awx.fullname" . }}
            items:
              - key: settings.py
                path: settings.py
              - key: secret_key
                path: SECRET_KEY
