apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "awx.fullname" . }}-secret-key
  labels:
    app.kubernetes.io/name: {{ include "awx.name" . }}
    helm.sh/chart: {{ include "awx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  SECRET_KEY: {{ .Values.secret_key | b64enc | quote }}
