apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "awx.fullname" . }}-secret-key
  labels:
    app.kubernetes.io/name: {{ include "awx.name" . }}
    helm.sh/chart: {{ include "awx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if not .Values.defaultAdminExistingSecret }}
  AWX_ADMIN_USER: {{ default .Values.default_admin_user .Values.defaultAdminUser | b64enc | quote }}
  AWX_ADMIN_PASSWORD: {{ default .Values.default_admin_password .Values.defaultAdminPassword | b64enc | quote }}
  {{- end }}
  {{- if not .Values.secretKeyExistingSecret }}
  SECRET_KEY: {{ default .Values.secret_key .Values.secretKey | b64enc | quote }}
  {{- end }}
  {{- if not .Values.postgresqlExistingSecret }}
  DATABASE_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DATABASE_NAME: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{- if .Values.postgresql.postgresqlHost }}
  DATABASE_HOST: {{ .Values.postgresql.postgresqlHost | b64enc | quote }}
  {{ else }}
  DATABASE_HOST: {{ printf "%s-postgresql" .Release.Name | b64enc | quote }}
  {{ end -}}
  DATABASE_PORT: {{ .Values.postgresql.service.port | toString | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DATABASE_ADMIN_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{- end }}
