apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awx.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "awx.name" . }}-web
    helm.sh/chart: {{ include "awx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "awx.name" . }}-web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "awx.name" . }}-web
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: awx
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: 8052
              name: http
          # livenessProbe:
          #   initialDelaySeconds: 5
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   initialDelaySeconds: 10
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
{{ include "awx.volumeMounts" . | indent 12 }}
{{- if .Values.web.extraVolumeMounts }}
{{ toYaml .Values.web.extraVolumeMounts | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.web.resources | indent 12 }}
    {{- if .Values.web.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.web.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.web.affinity }}
      affinity:
{{ toYaml .Values.web.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.web.tolerations }}
      tolerations:
{{ toYaml .Values.web.tolerations | indent 8 }}
    {{- end }}
      volumes:
{{ include "awx.volumes" . | indent 8 }}
{{- if .Values.web.extraVolumes }}
{{ toYaml .Values.web.extraVolumes | indent 8 }}
{{- end }}
