apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "github-actions-runner.fullname" . }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
data:
  registration_token: "{{ .Values.runner.registrationToken | b64enc }}"
