apiVersion: v1
appVersion: "1.0"
description: Add chart for deploying distributed Ansible AWX application.
name: awx
version: 0.2.0
maintainers:
  - name: Josh Bielick
    url: https://github.com/jbielick

