apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "faktory.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "faktory.name" . }}
    helm.sh/chart: {{ include "faktory.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if not .Values.passwordExistingSecret }}
  password: {{ include "faktory.password" . | b64enc | quote }}
{{- end -}}
{{- if and .Values.license (not .Values.licenseExistingSecret) }}
  license: {{ .Values.license | b64enc | quote }}
{{- end }}
