apiVersion: v1
kind: Service
metadata:
  name: {{ include "faktory.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "faktory.name" . }}
    helm.sh/chart: {{ include "faktory.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 7419
      name: tcp-server
      targetPort: server
      protocol: TCP
{{- if .Values.metrics.enabled }}
    - port: 9386
      name: http-metrics
      targetPort: metrics
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "faktory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
