apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rails.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  {{- toYaml .Values.secrets | nindent 2 }}
